# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d175cfd01a2d6e0381132961aa0dfa32cb7855353305e40003b32b13e4951f8b2408cff546c6e203933ddac7fc3dbd54dbc7ece4e0fe0a24f05610c5a0ef2d58

test:
  secret_key_base: 8b179d0b662e385236433518f33e4893edf8e5a4f6364069978388463c401300731520c7f65ec08bc245dde7c5004b537d03b00a061ef0507285f7422febf51c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
